# Generated by Django 5.0.6 on 2024-05-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full name')),
                ('dob', models.DateTimeField(verbose_name='Date of birth')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Customer email')),
                ('aadhaar', models.CharField(max_length=12, verbose_name='Customer aadhaar')),
                ('reg_date', models.DateTimeField(verbose_name='Registration date')),
                ('mob', models.CharField(max_length=10, unique=True, verbose_name='Customer mobile number')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Plan name')),
                ('cost', models.IntegerField(verbose_name='Plan cost')),
                ('validity', models.IntegerField(verbose_name='Plan validity')),
                ('status', models.CharField(choices=[('Inactive', 'Inactive')], verbose_name='Plan status')),
            ],
        ),
    ]
