# Generated by Django 5.0.6 on 2024-05-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_customerplans'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='plan',
            field=models.ManyToManyField(to='cms.plan'),
        ),
        migrations.DeleteModel(
            name='CustomerPlans',
        ),
    ]
